### ISSUE TITLE
add_image error

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaclient#30]
Kills Optimizer.py

```
Traceback (most recent call last):
  File "optimizer.py", line 737, in <module>
    run_local=args.run_local,
  File "optimizer.py", line 693, in main
    dota_optimizer.run()
  File "optimizer.py", line 507, in run
    self.writer.add_image('canvas', canvas, it, dataformats='HWC')
TypeError: add_image() got an unexpected keyword argument 'dataformats'
```

**Comment by Nostrademous** [comment]
Hm... apparently I had `tensorboardX version 1.5`. Upgrading to 1.6 fixed that issue.

```
Traceback (most recent call last):
  File "optimizer.py", line 737, in <module>
    run_local=args.run_local,
  File "optimizer.py", line 693, in main
    dota_optimizer.run()
  File "optimizer.py", line 507, in run
    self.writer.add_image('canvas', canvas, it, dataformats='HWC')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboardX/summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboardX/summary.py", line 250, in make_image
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Hit that next. Then had to install `pip install pillow`, which fixed that issue.
