### ISSUE TITLE
Error enemy reward calculation

### ISSUE THREAD

**Issue by Nostrademous** [TimZaman/dotaclient#35]
Occasionally

```
Traceback (most recent call last):
  File "agent.py", line 751, in main
    await game.play(game_id=game_id)
  File "agent.py", line 684, in play
    rad_rew = sum(players[TEAM_RADIANT].rewards[-1].values())
IndexError: list index out of range
```

**Comment by Nostrademous** [comment]
Can't reproduce....

**Comment by Nostrademous** [comment]
Happened again two days ago on 362nd game
```
Traceback (most recent call last):
  File "agent.py", line 797, in main
    await game.play(game_id=game_id)
  File "agent.py", line 730, in play
    rad_rew = sum(players[TEAM_RADIANT].rewards[-1].values())
IndexError: list index out of range
```
